name: Build and Package Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: jdx/mise-action@v2

      - name: Install Dependencies
        run: npm ci

      - name: Build Extension
        run: npm run package

      - name: Package Extension with VSCE
        run: npx @vscode/vsce package --no-dependencies

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: repomix-runner-vsix
          path: '*.vsix'